export const MainCarouselData = [
    {
        image:"https://marketplace.canva.com/EAFGKRRskMs/1/0/1600w/canva-brown-and-beige-minimalist-fashion-banner-lYcbGpUSVGo.jpg",
        path:"/women/clothing/dress"
    },
    {
        image:"https://marketplace.canva.com/EAFZzTbRz-g/1/0/1600w/canva-brown-minimalist-fashion-sale-banner-c4P9XubM0YE.jpg",
        path:"/women/clothing/dress"
    },
    {   
        image:"https://marketplace.canva.com/EAFLU0NpTbE/1/0/1600w/canva-brown-modern-new-brand-fashion-banner-u97g9GPKB4g.jpg",
        path:"/women/clothing/dress"
    },
    {
        image:"https://marketplace.canva.com/EAFoEJMTGiI/1/0/1600w/canva-beige-aesthetic-new-arrival-fashion-banner-landscape-cNjAcBMeF9s.jpg",
        path:"/women/clothing/dress"
    },
    {
        image:"https://marketplace.canva.com/EAFoustdoMc/1/0/1600w/canva-beige-aesthetic-fashion-style-banner-landscape-k4EiS0uPqD0.jpg",
        path:"/women/clothing/dress"
    },
]